Map<String, String> koreanfromkey = {
  "id": "식별자",
  "ingredient": "식재료",
  "location": "산지",
  "catch_month": "수확월",
  "maker": "제조사",
  "detail_category": "세부분류",
  "all_quantity_g": "총량(g)",
  "all_quantity_ml": "총량(ml)",
  "category": "분류",
  "unit_quantity": "1회 제공량",
  "unit": "단위",
  "calories": "열량",
  "moisture": "수분",
  "protein": "단백질",
  "fat": "지방",
  "carbonhydrate": "탄수화물",
  "fiber": "식이섬유",
  "calcium": "칼슘",
  "amino_acid": "아미노산",
  "trans_fatty_acid": "트랜스지방산",
  "unsaturated_fatty_acid": "불포화지방산",
  "sugar": "당류",
  "salt": "나트륨",
  "colesterol": "콜레스테롤",
  "fatty_acid": "포화지방산",
  "source": "출처",
  "issuer": "발행기관",
};
